Pablo.md : Eliminamos las pruebas
alvarezgpablorodrigo/PullRequest pull request #2
Opened 2022-04-27 19:16 UTC by PabloAlvarezG

Para este commit se elimino al autor intelectual del crimen ..

2022-04-27 19:17 UTC, alvarezgpablorodrigo commented on Pablo.md
> -2. YUKERO
Porque eliminaste al yukero aea aea

2022-04-27 19:17 UTC, alvarezgpablorodrigo commented on Pablo.md
> -3. LORD JUVE
porque eliminaste al dios juve gaaaa

2022-04-27 19:17 UTC, alvarezgpablorodrigo commented on Pablo.md
>  4. PAMELLENA
esta bien no mas esa perra

2022-04-27 19:19 UTC, PabloAlvarezG commented on Pablo.md
> -3. LORD JUVE
se considero elimiarna lord juve , porque tambien se entiende que es el yukero

2022-04-27 19:20 UTC, PabloAlvarezG commented on Pablo.md
>  4. PAMELLENA
# PAMELLENA
esta bien nomas , algo plana y pide mucho la perra de mierda

2022-04-27 19:21 UTC, PabloAlvarezG commented on Pablo.md
> -2. YUKERO
# YUKERO
Se elimino a yukero porque la amore lo conoce como yukero @alvarezgpablorodrigo

2022-04-27 19:23 UTC, alvarezgpablorodrigo requested changes
# YUKERO
Necesito que re integres a yukero y ahora lo llames KING JUVE

2022-04-28 00:41 UTC, merged

2022-04-28 00:41 UTC, alvarezgpablorodrigo commented
exito